name: CI for dbtf Models

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run dbtf CI Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install dbt-fusion CLI (dbtf)
        run: |
          curl -fsSL https://public.cdn.getdbt.com/fs/install/install.sh | sh -s -- --update
          mkdir -p ~/.local/bin
          ln -s ~/.local/bin/dbt ~/.local/bin/dbtf  # Symlink so we can use `dbtf` as command
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Confirm dbtf installed
        run: ~/.local/bin/dbtf --version

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Create Snowflake profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
          real_estate_valuation_fusion:
            target: dev
            outputs:
              dev:
                type: snowflake
                account: "${{ secrets.SNOWFLAKE_ACCOUNT }}"
                user: "${{ secrets.SNOWFLAKE_USER }}"
                password: "${{ secrets.SNOWFLAKE_PASSWORD }}"
                role: "${{ secrets.SNOWFLAKE_ROLE }}"
                database: REAL_ESTATE_VAL_DEV
                warehouse: COMPUTE_WH
                schema: STAGING
                threads: 4
          EOF

      - name: Run dbt debug
        run: ~/.local/bin/dbtf debug --profiles-dir ~/.dbt --profile real_estate_valuation_fusion --target dev
      - name: Run dbt compile
        run: ~/.local/bin/dbtf compile --target dev --log-level INFO

      - name: Run data tests
        run: ~/.local/bin/dbtf test --select tag:data_tests --target dev --log-level INFO

      - name: Run unit tests
        run: ~/.local/bin/dbtf test --select tag:unit_tests --target dev --log-level INFO