name: CI for real_estate_valuation_fusion

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - dev

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dbt Fusion
        run: |
          curl -fsSL https://public.cdn.getdbt.com/fs/install/install.sh | sh -s -- --update
          echo "/home/runner/.local/bin" >> $GITHUB_PATH

      - name: Check dbt Fusion version
        run: |
          /home/runner/.local/bin/dbtf --version

      - name: Create profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
          real_estate_valuation_fusion:
            outputs:
              dev:
                type: snowflake
                account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
                user: ${{ secrets.SNOWFLAKE_USER }}
                password: ${{ secrets.SNOWFLAKE_PASSWORD }}
                role: ${{ secrets.SNOWFLAKE_ROLE }}
                database: REAL_ESTATE_VAL_DEV
                warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
                schema: STAGING
                threads: 4
              prod:
                type: snowflake
                account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
                user: ${{ secrets.SNOWFLAKE_USER }}
                password: ${{ secrets.SNOWFLAKE_PASSWORD }}
                role: ${{ secrets.SNOWFLAKE_ROLE }}
                database: REAL_ESTATE_VAL_PROD
                warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
                schema: STAGING
                threads: 4
            target: dev
          EOF

      - name: Run dbt debug
        run: /home/runner/.local/bin/dbtf debug --profiles-dir ~/.dbt --profile real_estate_valuation_fusion --target dev

      - name: Run dbt compile
        run: /home/runner/.local/bin/dbtf compile --target dev

      - name: Run data tests
        run: /home/runner/.local/bin/dbtf test --select tag:data_tests --target dev

      - name: Run unit tests
        run: /home/runner/.local/bin/dbtf test --select tag:unit_tests --target dev
